# Generated by Django 3.1.5 on 2021-01-17 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doses_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('postcode', models.CharField(max_length=10)),
                ('assigned_centre', models.IntegerField()),
            ],
        ),
    ]
