# Generated by Django 3.1.5 on 2021-01-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxitrack', '0006_auto_20210119_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Centre_Name', models.CharField(max_length=30)),
                ('Post_Code', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=40)),
                ('VT_ID', models.CharField(max_length=30)),
            ],
        ),
    ]
