# Generated by Django 3.1.5 on 2021-01-20 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxitrack', '0007_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='VT_ID',
            new_name='VaxiTrack_ID',
        ),
    ]
