# Generated by Django 3.1.5 on 2021-01-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxitrack', '0009_userf'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VaxiTrack_ID', models.CharField(max_length=30)),
                ('Doses_Today', models.CharField(max_length=30)),
                ('Time_Available', models.CharField(max_length=40)),
                ('Vax_Type', models.CharField(max_length=10)),
            ],
        ),
    ]
