# Generated by Django 3.1.5 on 2021-01-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxitrack', '0012_auto_20210122_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='VaxiTrack_ID',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='centre',
            name='doses_available',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_centre',
            field=models.CharField(default='', max_length=10),
        ),
    ]
