# Generated by Django 3.1.5 on 2021-01-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxitrack', '0013_auto_20210122_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centres', models.BigIntegerField(default=0)),
                ('vaccines', models.BigIntegerField(default=0)),
                ('patients', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='centre',
            name='available_at',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='centre',
            name='doses_available',
            field=models.CharField(default='', max_length=10),
        ),
    ]
