# Generated by Django 3.1.5 on 2021-01-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxitrack', '0015_auto_20210123_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='centre_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_centre_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_centre_postcode',
        ),
        migrations.AlterField(
            model_name='centre',
            name='VaxiTrack_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='centre',
            name='available_at',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='centre',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='centre',
            name='vax_type',
            field=models.IntegerField(choices=[(1, 'Oxford Astrazeneca'), (2, 'Pfizer')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_centre_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
