# Generated by Django 3.1.5 on 2021-01-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxitrack', '0015_auto_20210123_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='centre_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='centre',
            old_name='VaxiTrack_ID',
            new_name='vaxitrack_ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_centre_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_centre_postcode',
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_centre_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
