# Generated by Django 3.1.5 on 2021-01-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxitrack', '0016_auto_20210123_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='vaxitrack_ID',
        ),
    ]
