# Generated by Django 3.1.5 on 2021-01-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxitrack', '0016_auto_20210124_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_centre_id',
            field=models.IntegerField(default=0),
        ),
    ]
