# Generated by Django 3.1.5 on 2021-02-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxitrack', '0017_auto_20210124_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key_worker',
            field=models.BooleanField(default=0),
        ),
    ]
